### ISSUE TITLE
Appstats not working anymore

### ISSUE THREAD

**Issue by nicow2** [tmurakam/googleplay_dev_scraper#4]
As of yesterday the appstats download is not working anymore. I'd guess the URL has changed. If I try to access the url directly in the browser I see a Google Error Page saying:
400. That’s an error.

The requested URL was not found on this server. That’s all we know. 

Please finde the Console Output of the scraper below:

URL = https://play.google.com/apps/publish/v2/statistics/download?package=my.package&sd=20130804&ed=20130804&dim=overall,country,language,os_version,device,app_version,carrier&met=active_device_installs,daily_device_installs,daily_device_uninstalls,daily_device_upgrades,active_user_installs,total_user_installs,daily_user_installs,daily_user_uninstalls,daily_avg_rating,total_avg_rating
/var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:306:in `fetch': 400 => Net::HTTPBadRequest for https://play.google.com/apps/publish/statistics/download?package=my.package&sd=20130804&ed=20130804&dim=overall,country,language,os_version,device,app_version,carrier&met=active_device_installs,daily_device_installs,daily_device_uninstalls,daily_device_upgrades,active_user_installs,total_user_installs,daily_user_installs,daily_user_uninstalls,daily_avg_rating,total_avg_rating -- unhandled response (Mechanize::ResponseCodeError)
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:974:in`response_redirect'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:298:in `fetch'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:974:in`response_redirect'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:298:in `fetch'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:974:in`response_redirect'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:298:in `fetch'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize.rb:1272:in`post_form'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize.rb:539:in `submit'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/form.rb:223:in`submit'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/form.rb:229:in `click_button'
    from /var/lib/gems/1.9.1/gems/googleplay_scraper-0.2.2/lib/googleplay_scraper/scraper_base.rb:55:in`try_get'
    from /var/lib/gems/1.9.1/gems/googleplay_scraper-0.2.2/lib/googleplay_scraper/scraper.rb:156:in `get_appstats'
    from /var/lib/gems/1.9.1/gems/googleplay_scraper-0.2.2/bin/googleplay_scraper:136:in`appstats'
    from /var/lib/gems/1.9.1/gems/googleplay_scraper-0.2.2/bin/googleplay_scraper:41:in `main'
    from /var/lib/gems/1.9.1/gems/googleplay_scraper-0.2.2/bin/googleplay_scraper:146:in`<top (required)>'
    from /usr/local/bin/googleplay_scraper:23:in `load'
    from /usr/local/bin/googleplay_scraper:23:in`<main>'

Thanks for your effort.
Kind regards
Nicow

**Comment by tmurakam** [comment]
URL fixed with commit 873050f80403dd90cdae24a514e9e94dac582d37
