### ISSUE TITLE
Cant seek estimated Sales Report

### ISSUE THREAD

**Issue by zdravko81** [tmurakam/googleplay_dev_scraper#5]
Hi, I cant "scrape" the estimated Sales Report. The Url cant be found. 
I'd guess the URL has changed. If I try to access the url directly in the browser I see a Google Error Page saying:
400. That’s an error.

The requested URL was not found on this server. That’s all we know. 

Please find the Console Output of the scraper below:

`fetch': 400 => Net::HTTPBadRequest for https://play.google.com/apps/publish/salesreport/download?report_date=2013_08&report_type=sales_report&dev_acc=00158313850196121289 -- unhandled response (Mechanize::ResponseCodeError)
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:974:in`response_redirect'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:298:in `fetch'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:974:in`response_redirect'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:298:in `fetch'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:974:in`response_redirect'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/http/agent.rb:298:in `fetch'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize.rb:1272:in`post_form'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize.rb:539:in `submit'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/form.rb:223:in`submit'
    from /var/lib/gems/1.9.1/gems/mechanize-2.7.1/lib/mechanize/form.rb:229:in `click_button'
    from /var/lib/gems/1.9.1/gems/googleplay_dev_scraper-1.0.2/lib/googleplay_dev_scraper/scraper_base.rb:55:in`try_get'
    from /var/lib/gems/1.9.1/gems/googleplay_dev_scraper-1.0.2/lib/googleplay_dev_scraper/scraper.rb:55:in `get_estimated_sales_report'
    from /var/lib/gems/1.9.1/gems/googleplay_dev_scraper-1.0.2/bin/googleplay_dev_scraper:93:in`estimated'
    from /var/lib/gems/1.9.1/gems/googleplay_dev_scraper-1.0.2/bin/googleplay_dev_scraper:33:in `main'
    from /var/lib/gems/1.9.1/gems/googleplay_dev_scraper-1.0.2/bin/googleplay_dev_scraper:122:in`<top (required)>'
    from /usr/local/bin/googleplay_dev_scraper:23:in `load'
    from /usr/local/bin/googleplay_dev_scraper:23:in`<main>'

**Comment by tmurakam** [comment]
Fixed with 7b0d9602d5ae702a19cc35ae13eb7fa0ae7b156b, and released as ver 1.0.3.
